apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:gc1T5pt8eKCzEHD5,iv:6mUPn/JuYSE3ssH0McMLKFfPR5Lv/xv3KH+08W2cFdA=,tag:rqGl/9MDDyWfozMcBGJZtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ttnu6zks7sngsrhk3wgh3acg4hhqsc87elv3007c4p884czs4v8s3dl6hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2enpLdkdhbDNjWCsrTDBP
            UEF5SFRsK1ZEdnM3WDF2L3RhaEJPNWFHU1RBCjB6Vm1pK2FsVmJwV2NldGF4eS96
            cmJwNVEvTFhiZ1pQKzl1UndDSmVyYmcKLS0tIERVRm8xNzZLZkR6VFU0aFp6M1NO
            dkhhMmUxdjg3Z0VQaXZwd0MrbzN0c3MKVumm9qc4+V2+XPRG81xY5g3zU5WFUUIC
            r8sYFG37WSTvCkTOU8YJ8nAdan8y2aJfkullgmhK7w+EN+dOtnC+HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T11:50:04Z"
    mac: ENC[AES256_GCM,data:l8/YFc7dNgfk6nmqJU7YQ43bwHRV3Cf/3+Z45QsP4J6F8mJZ3M/lOYQPKxB3gPtDra6poZXponNpDpvu9XV3aJHwt09itq1TTH6k1GuHo9Ii1dt1dFt+aiRn98pnK8Rem+HOthA3MuoNo/rwUh6MIfMAMuYjJC3XM/ATtEAT8vk=,iv:Biv43gjS5pzlJXl02DigaYa7ISUSTIcNeHrc3rZGwGw=,tag:/E4yEJjovLsWtfRQGvHBWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
